variables:
  NAME: mosaic:3.3.0-SNAPSHOT
stages:
  - build
  - container
build:
  image: node:6
  stage: build
  script:
    - npm config set registry http://192.168.1.6:8081/repository/npm-group/
    - npm config set disturl https://npm.taobao.org/dist
    - npm config set electron_mirror https://npm.taobao.org/mirrors/electron/
    - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - npm config set phantomjs_cdnurl https://npm.taobao.org/mirrors/phantomjs/
    - npm config set chromedriver_cdnurl http://npm.taobao.org/mirrors/chromedriver
    - npm config set sass_binary_site=http://npm.taobao.org/mirrors/node-sass
    - npm install --progress=false
    - npm run build
  cache:
    key: mosaic
    paths:
      - node_modules
  only:
    - develop
    - master
    - /^release-.*$/
  artifacts:
    expire_in: 1 week
    paths:
      - dist
    

container:
  image: docker
  stage: container
  script:
    - docker login -u admin -p admin123 192.168.1.6:5000
    - docker build -t 192.168.1.6:5000/tangram/$NAME .
    - docker push 192.168.1.6:5000/tangram/$NAME
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 47.97.167.23:5000
    - docker tag 192.168.1.6:5000/tangram/$NAME 47.97.167.23:5000/tangram/$NAME
    - docker push 47.97.167.23:5000/tangram/$NAME
  only:
    - develop
    - master
    - /^release-.*$/
